app/main/routes.py
import base64
import binascii
import datetime
import hashlib
import os
import subprocess

from flask import current_app, render_template, Blueprint, jsonify, request, send_from_directory
from flask_login import current_user
from flask_user import login_required

from app import db
from app.main.concatenator import tts, MissingPhonemeError, MissingPhonemeRecordingError, UnknownWordError
from app.main.models import PhonemeRecording, Phoneme

bp = Blueprint('main', __name__, url_prefix="/")


@bp.route('/synthesiser', methods=["GET", "POST"])
@login_required
def synthesiser():
    if request.method == "GET":
        return render_template("main/synthesiser.html")

    text_input = request.form.get("text_input", "", str)

    current_app.logger.info(f"Speech synthesis requested for '{text_input}' by {current_user}")

    if not text_input:
        current_app.logger.debug(f"400 returned due to text being empty")
        return jsonify({"msg": "Text cannot be empty!"}), 400

    try:
        phonemes, file_addresses = tts(text_input)
    except UnknownWordError as error_word:
        current_app.logger.debug(f"Unknown word identified '{error_word}'")
        return jsonify({"code": 1, "msg": f"Unknown word provided!<br>{error_word}<br>"
                                          "Please only use words found in the Oxford Dictionary"}), 400
    except MissingPhonemeError:
        current_app.logger.warning(f"Missing phoneme error occurred!")
        return jsonify({"code": 1, "msg": "Unknown phoneme identified!"}), 400
    except MissingPhonemeRecordingError as error:
        current_app.logger.debug(f"User has not recorded phoneme {error.phoneme.symbol}")
        return jsonify({"code": 2, "msg": str(error), "phoneme_id": error.phoneme.id,
                        "symbol": error.phoneme.symbol}), 400

    relative_address = file_addresses["relative_address"]
    current_app.logger.info(f"Speech synthesis completed successfully for {current_user}")

    return jsonify({"text_input": text_input, "file": relative_address, "phonemes": phonemes}), 200


@bp.route('/concatenation_setup')
@login_required
def concatenation_setup():
    phonemes = Phoneme.query.all()
    return render_template("main/concatenation_setup.html", phonemes=phonemes)


@bp.route("/save_recording", methods=["POST"])
@login_required
def save_recording():
    """saves the provided phoneme recording audio stream into the users' personal directory under a random name"""

    phoneme_id = request.form.get("phoneme_id", 0, int)
    phoneme = Phoneme.query.filter_by(id=phoneme_id).first()

    if not phoneme:
        return jsonify({"msg": "Unknown phoneme id supplied!"}), 400

    current_app.logger.info(f"Recording save request made for {phoneme} by {current_user}...")

    # random name is to prevent caching issues when re-recording a phoneme
    random_name = hashlib.md5(str(datetime.datetime.utcnow()).encode('utf-8')).hexdigest().lower()
    file_name = f"{random_name}.{current_app.config.get('AUDIO_FILE_EXT')}"
    file_relative_address = current_user.relative_recording_dir
    file_address = os.path.join(current_app.config.get("USER_DIR"), file_relative_address, file_name)

    try:
        audio_stream = request.form.get("audio", "", str)
        audio_stream = audio_stream.replace(f"data:{current_app.config.get('AUDIO_MIME_TYPE')};base64,", "")
        audio_binary = base64.decodebytes(audio_stream.encode("utf-8"))

        current_app.logger.info("Going to build...")
        current_user.ensure_dir_is_built()
        current_app.logger.info("Hmm!")
        with open(file_address + ".temp", "wb") as file:
            file.write(audio_binary)

    except (OSError, binascii.Error):
        current_app.logger.exception("Error occurred whilst saving audio binary to file!")
        return jsonify({"msg": "Recording could not be saved successfully!"}), 400

    # crop audio cmd
    trim_start = request.form.get("start", 0, float)
    trim_end = request.form.get("end", 1, float)
    trim_cmd = f"-ss {trim_start:.2f} -to {trim_end:.2f}"

    # increase volume cmd for quiet phonemes [k]
    volume_cmd = f"-filter:a 'volume=2'" if phoneme_id in [16] else ""

    subprocess.call(f"ffmpeg -i \"{file_address}.temp\" {trim_cmd} -c copy \"{file_address}\" -y {volume_cmd} "
                    f"-hide_banner -loglevel verbose")

    os.remove(file_address + ".temp")

    # delete old recording if exists
    if phoneme_id in current_user.phoneme_recordings:
        try:
            os.remove(os.path.join(current_app.config["USER_DIR"],
                                   current_user.phoneme_recordings[phoneme_id].local_address))
        except FileNotFoundError:
            pass
        db.session.delete(current_user.phoneme_recordings[phoneme_id])

    current_user.phoneme_recording_objects.append(PhonemeRecording(file_relative_address, file_name, phoneme_id))

    db.session.commit()
    current_app.logger.info(f"Recording save request for {phoneme} by {current_user} completed successfully")

    return jsonify({"msg": "Recording successfully saved!"}), 200


@bp.route("user_data/<path:file>")
@login_required
def user_data(file):
    current_app.logger.debug(f"{current_user} requested {file}")

    relative_address_parts = file.split("/")

    if len(relative_address_parts) <= 2:
        return jsonify({"msg": "invalid file path"}), 400

    if "\\".join(relative_address_parts[:2]) != current_user.user_secure_dir:
        return jsonify({
            "msg": "Authorisation error! You are attempting to access a directory potentially belonging to another "
                   "user!"
        }), 403

    current_app.logger.debug(f"Sending {file} from {current_app.config['USER_DIR_NAME']}")
    return send_from_directory(current_app.config["USER_DIR_NAME"], file)

app/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user

from app.auth.forms import LoginForm

bp = Blueprint('app', __name__, url_prefix="/")


@bp.route('/')
@bp.route('/index')
def index():
    if current_user.is_authenticated:
        return redirect(url_for("main.synthesiser"))
    return render_template("index.html", form=LoginForm())

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="Personal Speech Synthesis is a webapp enabling easy speech synthesis personalised to the users voice.">
    <meta name="author" content="Daniel Samet">

    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for("apple-touch-icon") }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for("favicon-32x32") }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for("favicon-16x16") }}">
    <link rel="manifest" href="{{ url_for("site_webmanifest") }}">

    <title>PSS | Personal Speech Synthesis</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    {% block extra_css %}{% endblock extra_css %}

    <link href="{{ url_for("static", filename="css/main.css") }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
          integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
          crossorigin="anonymous"/>
</head>

<body class="bg-back d-flex flex-column min-vh-100">

<nav class="navbar navbar-expand-lg navbar-dark bg-second flex-grow-0 p-4">
    <div class="container px-4">
        <a class="navbar-brand fw-bold" href="{{ url_for("app.index") }}">
            <img src="{{ url_for("static", filename="media/logo.png") }}" alt="PSS" class="nav-logo" width="18em"
                 height="100%">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbar"
                aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            {% block navbar %}{% endblock navbar %}
        </div>
    </div>
</nav>

<section class="bg-white flex-grow-0 p-4">
    <div class="container px-4">
        {% block sub_section %}{% endblock sub_section %}
    </div>
</section>

<main class="container-fluid bg-foreground flex-grow-1 d-flex p-0">
    <div class="p-4 flex-grow-1 d-flex flex-column">
        {% block main_content %}{% endblock main_content %}
    </div>
</main>

<footer class="bg-second text-white p-3">
    <div class="row mb-0">
        <span class="col"><a href="https://github.com/CouchMaster789" class="text-white">Daniel Samet</a></span>
        <span class="col text-center">
            Full Paper available <a class="text-white" href="#" data-bs-toggle="tooltip" data-bs-placement="top"
                                    title="Coming Soon">here</a>
        </span>
        <span class="col text-end">
            <a href="https://www.qmul.ac.uk/" class="text-white">Queen Mary University of London</a>
        </span>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>
    let tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    let tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    });
</script>
{% block extra_js %}{% endblock extra_js %}
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block sub_section %}
    <h5 class="mb-0 text-center">
        This webapp is my final year project for Computer Science @ Queen Mary University of London. See my other
        projects
        <a href="#" class="link-success">here</a>.
    </h5>
{% endblock sub_section %}

{% block main_content %}
    <div class="container" style="max-width: 130em;">
        <div class="text-center mt-3 mx-auto" style="max-width: 80em;">
            <h1>Personal Speech Synthesis</h1>
            <h5 class="text-muted">
                A webapp built to ease the creation of personal speech synthesisers. This app will guide you through
                recording the relevant parts of your voice. This will then allow you to type new - unseen - text and
                synthesise real speech audio.
            </h5>
        </div>

        <div class="row justify-content-center mt-5">
            <div class="col-auto mt-5">
                <div class="card bg-second text-white">
                    <div class="card-header border-white">
                        <h4 class="mb-0">How it Works</h4>
                    </div>
                    <div class="card-body px-5">
                        <div class="row justify-content-center my-5">
                            <div class="col-auto text-center position-relative me-4">
                                <div class="row hiw-info">
                                    <div class="col-auto">
                                        <i class="fa fa-microphone-alt fa-5x"></i>
                                        <br>
                                        <br>
                                        <p class="fw-bold hiw-text">You'll be guided through recording your voice</p>
                                    </div>

                                    <div class="col-auto d-flex align-items-center h-100">
                                        <i class="fa fa-arrow-right fa-3x mx-4 text-white-50"></i>
                                    </div>
                                </div>
                                <span class="hiw-info-marker fs-6">once</span>
                            </div>

                            <div class="col-auto text-center position-relative">
                                <div class="row hiw-info">
                                    <div class="col-auto">
                                        <i class="fa fa-keyboard fa-5x"></i>
                                        <br>
                                        <br>
                                        <p class="fw-bold hiw-text">Type your desired text</p>
                                    </div>

                                    <div class="col-auto d-flex align-items-center h-100">
                                        <i class="fa fa-arrow-right fa-3x mx-4 text-white-50"></i>
                                    </div>

                                    <div class="col-auto">
                                        <i class="fa fa-volume-up fa-5x"></i>
                                        <br>
                                        <br>
                                        <p class="fw-bold hiw-text">Hear your speech synthesised</p>
                                    </div>
                                </div>

                                <span class="hiw-info-marker fs-6">repeat</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-auto mt-5">
                <form action="" method="POST" id="registration-login" class="h-100">
                    <div class="card form-card h-100 mx-auto">
                        <div class="card-header bg-second text-white">
                            <h4 class="mb-0">Start Now</h4>
                        </div>
                        <div class="card-body h-100 bg-light">
                            {{ form.hidden_tag() }}

                            <div class="mb-3">
                                <label for="email_address" class="form-label fw-bold">Email address</label>
                                {{ form.email_address(class_="form-control", type="email", id="email_address") }}
                                <label class="invalid-feedback">Invalid email address format</label>
                            </div>

                            <div class="mb-3">
                                <label for="password" class="form-label fw-bold">Password</label>
                                {{ form.password(class_="form-control", type="password", id="password") }}
                            </div>

                            <div class="mb-2 form-check">
                                <input type="checkbox" class="form-check-input" id="remember_me">
                                <label class="form-check-label" for="remember_me">Remember Me?</label>
                            </div>

                            <div class="mb-3">
                                <a class="link-dark" href="#">Forgot password?</a>
                            </div>

                            <div class="g-recaptcha" data-sitekey="{{ config["RECAPTCHA_PUBLIC_KEY"] }}"></div>

                            <div class="alert alert-danger mb-0 mt-2 visually-hidden" id="error_msg"></div>
                        </div>
                        <div class="card-footer bg-second text-white text-end">
                            <button type="button" class="btn btn-success btn-sm fw-bold me-2"
                                    onclick="form_submission('register')">
                                Register
                            </button>
                            <button type="button" class="btn btn-primary btn-sm fw-bold"
                                    onclick="form_submission('login')">
                                Login
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock main_content %}

{% block extra_js %}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <script>
        let email_address = $("#email_address");
        let password = $("#password");
        let csrf_token = $("#csrf_token");
        let remember_me = $("#remember_me");
        let error_msg = $("#error_msg");

        function validateEmail($email) {
            return /^([\w-\.]+@([\w-]+\.)+[\w-]{2,10})?$/.test($email) && $email !== "";
        }

        function form_submission(type) {
            let valid = true;
            error_msg.addClass("visually-hidden");

            if (!validateEmail(email_address.val())) {
                email_address.addClass("is-invalid");
                valid = false;
            } else
                email_address.removeClass("is-invalid");

            if (password.val() === "") {
                password.addClass("is-invalid");
                valid = false;
            } else
                password.removeClass("is-invalid");

            if (!valid)
                return;

            let url;
            if (type === "login")
                url = "{{ url_for("auth.login") }}";
            else
                url = "{{ url_for("auth.register") }}";

            $.post(url, {
                "email_address": email_address.val(),
                "password": password.val(),
                "csrf_token": csrf_token.val(),
                "remember_me": remember_me.is(":checked"),
                "recaptcha": grecaptcha.getResponse(),
            }).done(function (response) {
                window.location.href = "{{ url_for("main.synthesiser") }}";
            }).fail(function (response) {
                let msg = "An error occurred :(";

                if (Object.keys(response).includes("responseJSON"))
                    if (Object.keys(response.responseJSON).includes("msg"))
                        msg = response.responseJSON["msg"];

                error_msg.removeClass("visually-hidden");
                error_msg.text(msg);
            });
        }
    </script>
{% endblock %}

app/templates/synthesiser.html
{% extends "base.html" %}

{% block main_content %}
    <div class="alert alert-warning">
        <b>Note</b>: this project is still in progress and may not work as expected until v1.0 is released.
    </div>

    <div class="card bg-item">
        <div class="card-body p-4">
            <label class="h4 form-label fw-bold" for="synthesiser_text">Text To Synthesise:</label>
            <textarea class="form-control bg-light" id="synthesiser_text" rows="8"
                      placeholder="Enter text here for speech synthesis"></textarea>
        </div>
    </div>

    <div class="card bg-item my-4">
        <div class="card-body p-4">
            <div class="row justify-content-between">
                <div class="col-auto">
                    <button class="btn btn-primary fixed-btn fw-bold" id="synthesise_btn">Synthesise</button>
                </div>
                <div class="col-auto text-end invisible" id="btns-container">
                    <button class="btn btn-success fixed-btn fw-bold play-btn" id="play_btn">Play</button>
                    <button class="btn btn-secondary fw-bold pause-btn" id="pause_btn">Pause</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row invisible" id="result-container">
        <div class="col-8 flex-grow-1">
            <div class="card bg-item">
                <div class="card-body p-4 text-center">
                    <div id="waveform"></div>
                </div>
            </div>
        </div>
        <div class="col-4 flex-grow-1">
            <div class="card bg-item h-100">
                <div class="card-body">
                    <div class="row">
                        <div class="rating-col">
                            <label class="col-form-label fw-bold metric-label">Metric 1</label>
                        </div>
                        <div class="col">
                            <div class="rate mx-auto">
                                {% for index in range(5, 0, -1) %}
                                    <input type="radio" id="star{{ index }}" name="rate_metric_1" value="{{ index }}"
                                           {% if index == 4 %}checked{% endif %}/>
                                    <label for="star{{ index }}" title="text">{{ index }} stars</label>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="rating-col">
                            <label class="col-form-label fw-bold metric-label">Metric 2</label>
                        </div>
                        <div class="col">
                            <div class="rate mx-auto">
                                {% for index in range(10, 5, -1) %}
                                    <input type="radio" id="star{{ index }}" name="rate_metric_2"
                                           value="{{ index }}" {% if index == 7 %}checked{% endif %}/>
                                    <label for="star{{ index }}" title="text">{{ index }} stars</label>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="rating-col">
                            <label class="col-form-label fw-bold metric-label">Metric 3</label>
                        </div>
                        <div class="col">
                            <div class="rate mx-auto">
                                {% for index in range(15, 10, -1) %}
                                    <input type="radio" id="star{{ index }}" name="rate_metric_3"
                                           value="{{ index }}" {% if index == 13 %}checked{% endif %}/>
                                    <label for="star{{ index }}" title="text">{{ index }} stars</label>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main_content %}

{% block extra_js %}
    <script src="{{ url_for("static", filename="js/wavesurfer.js") }}"></script>
    <script src="{{ url_for("static", filename="js/ws.js") }}"></script>
    <script>
        window.addEventListener('DOMContentLoaded', () => {
            let synthesise_btn = $("#synthesise_btn");
            let text_input = $("#synthesiser_text");
            let btns_container = $("#btns-container");
            let wavesurfer;

            synthesise_btn.click(function () {
                $.post("{{ url_for("main.synthesiser") }}", {
                    "text_input": text_input.val()
                }).then(async function (response) {
                    console.log(response);

                    if (wavesurfer !== undefined)
                        wavesurfer.destroy();

                    let audio_url = "{{ url_for("static", filename="empty_file") }}".replace("empty_file", response["file"]);
                    let make_visible = [$("#result-container"), btns_container];
                    wavesurfer = await load_audio("waveform", audio_url, false, btns_container, make_visible);
                }).fail(function (response) {
                    console.log(response);
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: response["responseJSON"]["msg"],
                        footer: `<p class='text-center'>Go to the <a href='{{ url_for("main.concatenation_setup") }}'>concatenation</a> page to ensure all recordings are marked with a tick!</p>`
                    })
                });
            });
        });
    </script>
{% endblock extra_js %}